### ISSUE TITLE
More profile links

### ISSUE THREAD

**Issue by WilliamVenner** [DiscordStudios/scriptfodder-issues#12]
![](http://i.imgur.com/ixLGMti.png)

\+ any more you can think of/want

**Comment by Marcuzz** [comment]
Probably won't be done yet as it looks like absolute crap. We'll have a re-design at one point

**Comment by WilliamVenner** [comment]
Yeah it doesn't look good, I don't like the long list. At the moment it looks like four rows only looks nice.

**Comment by WilliamVenner** [comment]
This doesn't look too bad

![](http://i.imgur.com/kAiBggo.png)

**Comment by Marcuzz** [comment]
Nope, not gonna be it. That space is already reserved for badges, which is a system we already have implemented, just haven't put to  use

**Comment by Marcuzz** [comment]
![Badge](https://marcuz.eu/files/StEQ.png)

**Comment by WilliamVenner** [comment]
I'll keep suggesting stuff as they come to mind.

![](http://i.imgur.com/QtdIPt5.png)

**Comment by Marcuzz** [comment]
nah, I don't want to touch the design until we rework it, it's not going to stay like this forever, because quite frankly it's horse shit right now

**Comment by HandsomeMatt** [comment]
not a social media club
