### ISSUE TITLE
Double escaping of double quotes - Markdown

### ISSUE THREAD

**Issue by EstevanTH** [DiscordStudios/scriptfodder-issues#13]
Hello,

I got a problem with my new script on ScriptFodder. [my script](https://scriptfodder.com/scripts/view/625)
In the description, double quotes are escaped twice so that all `"` are replaced by `&quot;`. I do not know if this only happens in source code or also for regular text.

The problem does not happen in the preview, it does only in the description in the final page.
Also, when I edit my script, the double quotes appear correctly, so the double escape does not happen when saving, but only when displaying the script description on its page.

**Comment by JamieH** [comment]
Should be fixed now.

**Comment by EstevanTH** [comment]
It took 5 months to fix, but the result is good. :stuck_out_tongue_closed_eyes:
