### ISSUE TITLE
Option to inject LICENSE file elsewhere

### ISSUE THREAD

**Issue by WilliamVenner** [DiscordStudios/scriptfodder-issues#13]
Most addons will have their file structure like this when downloaded:

![](http://i.imgur.com/s7C7xWn.png)

It would be helpful if there was an option to move the LICENSE file elsewhere. For the above example, I would change it to "_blogs_revamped-2-6" which would place the LICENSE file in that folder.

**Comment by Marcuzz** [comment]
Just put the contents of the folder into the main directory then, geez. We're not making a useless feature to move the license file

**Comment by WilliamVenner** [comment]
Most addon authors (like me) use a folder because then you see this disgusting shit in people's addon folders:

![](http://i.imgur.com/LxCGPiq.png)

**Comment by Marcuzz** [comment]
We're not gonna make a feature to move the license file, it's not gonna happen
