### ISSUE TITLE
Can't report job request

### ISSUE THREAD

**Issue by AlexCoder25** [DiscordStudios/scriptfodder-issues#17]
According to no info about this bug in #5 

Clicking the red REPORT button on the job page show next:
Error!
This page does not exist!
Click here to go back.

Where "here" is referer to https://scriptfodder.com/ajax/notifications-count with JSON:
{
    "status": "success",
    "notification_count": "0",
    "messages_count": "0",
    "tickets_count": "0",
    "dev_tickets_count": "0",
    "all_count": 0
}

**Comment by JamieH** [comment]
It's a known issue and will be fixed with an upcoming update.
