### ISSUE TITLE
<br> Works in preview only

### ISSUE THREAD

**Issue by Partixel** [DiscordStudios/scriptfodder-issues#21]

**Comment by Partixel** [comment]
![image](https://cloud.githubusercontent.com/assets/2728862/7660158/671c2b9e-fb3f-11e4-838f-bcab5c90862a.png)
![image](https://cloud.githubusercontent.com/assets/2728862/7660159/6bc86b44-fb3f-11e4-9278-95c2fab14505.png)

**Comment by JamieH** [comment]
You should end the line with 2 or more spaces to get the same effect.
