### ISSUE TITLE
Cant Pay

### ISSUE THREAD

**Issue by Skyborder** [DiscordStudios/scriptfodder-issues#28]
Hello the Germany Persons cant pay Addons on your Site
Say you what this is

**Comment by HandsomeMatt** [comment]
this is nice and descriptive

could u provide more details

**Comment by Skyborder** [comment]
HandsomeMatt
My Name is on Scriptfodder Stylermaler:
I will payed the Script from Drover the Food System and this System say

Error(s) occurred while checking out:
The receiver droversad@gmail.com does not accept payments in this Currency
Please notify Drover about this 

Germany have €
And US $

What can i do

**Comment by HandsomeMatt** [comment]
contact Drover about it quoting that

**Comment by Skyborder** [comment]
i have and the person have no Idea

**Comment by Marcuzz** [comment]
link him to this:

https://scriptfodder.com/knowledgebase/article/2/setting-up-paypal-payments

**Comment by Skyborder** [comment]
Thanks my Friend Marcuzz :+1:

**Comment by Skyborder** [comment]
Marcuz Hero say Thanks and you can close
