### ISSUE TITLE
The receiver (mail) does not accept payments in this Currency

### ISSUE THREAD

**Issue by DefaltNF** [DiscordStudios/scriptfodder-issues#30]
Hello,

Since yesterday I can't buy any script, I have this error : 
http://image.prntscr.com/image/1174dad9b8c9424faf53ff47e2c0544f.png

I tried to buy in EUR and USD but same error.

Thank's for your help !

**Comment by Marcuzz** [comment]
AwPanda hasn't configured his PayPal account to accept the USD currency properly. When it says specifically to contaft AwPanda, it means to contact AwPanda. Not us.
