### ISSUE TITLE
China user cant purchase any addon..

### ISSUE THREAD

**Issue by takaqiao** [DiscordStudios/scriptfodder-issues#32]
paypal dont let me purchase.. But i cant translate it to English

**Comment by HandsomeMatt** [comment]
show the error

**Comment by ExtReMLapin** [comment]
He's one of my clients, he used to buy my addons, and i had a problem myself with paypal, even after enabling "Put this currency into mine if i don't have it..." i was not able to buy my own addon, i had to add the USD currency on paypal.

And then only it worked.

**Comment by WilliamVenner** [comment]
#30 #28

**Comment by HandsomeMatt** [comment]
you mean as described in the knowledge base article that's been linked 50 times the past few days

**Comment by WilliamVenner** [comment]
@HandsomeMatt https://github.com/DiscordStudios/scriptfodder-issues/pull/31

**Comment by takaqiao** [comment]
Not e-mail problem
I think sth limit the payment
I could pay for anything in any website except scriptfodder
I could purchase items in G2A or pay for goods to someone..
And I cant purchase every addons

**Comment by takaqiao** [comment]
Not e-mail problem
I think sth limit the payment
I could pay for anything in any website except scriptfodder
I could purchase items in G2A or pay for goods to someone..
And I cant purchase every addons

**Comment by takaqiao** [comment]
@HandsomeMatt @WilliamVenner

**Comment by takaqiao** [comment]
Now i purchase addons by contacting author..
Ofc some authors dont trust me..

**Comment by Marcuzz** [comment]
You might have issues because of your location. Where are you located?
This will be fixed soon anyways as we're changing how things work a bit.

**Comment by takaqiao** [comment]
And it happens after updating
So it must be something wrong after updating(maybe country block?or sth)

**Comment by takaqiao** [comment]
@Marcuzz China

**Comment by Marcuzz** [comment]
Does this happen AFTER signing in to PayPal or BEFORE?

**Comment by takaqiao** [comment]
After

**Comment by takaqiao** [comment]
after i press the purchase buttom

**Comment by takaqiao** [comment]
@Marcuzz After pressing the purchase buttom (after signing in)

**Comment by takaqiao** [comment]
Anyone could help me~~~ Thanks~

**Comment by HandsomeMatt** [comment]
We're working on an update, but PayPal currently restricts Chinese users
from purchasing from us.

**Comment by takaqiao** [comment]
Thanks
